global: 
  scrape_interval: 15s
  scrape_timeout: 12s
  external_labels: 
    env: Cloud
    
  remote_write:
    write_relabel_configs:
    - source_label: [__name__]
      regex: to_expensive_to_write_to_long_term_storage.*
      action: drop

rule_files:
  - /etc/prometheus/cloud.rules  
  - /etc/prometheus/sample.rules

scrape_configs:
  - job_name: 'nodex'
    dns_sd_configs:
    - names: 
      - 'tasks.nodex'
      type: 'A'
      port: 9100

  - job_name: 'cloudPlatform'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    metrics_path: '/metrics/cloudstack'
    static_configs:
      - targets: ['cloudstack_filter-proxy:8080']
    metric_relabel_configs: 
    - regex: 'container_label_com_docker_(.*)'
      action: labelmap
      replacement: 'cl_cd_${1}'

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'rabbit2mongo'
    dns_sd_configs:
    - names:  
      - 'tasks.cloudstack_rabbit2mongo'
      type: 'A'
      port: 8080
      #TODO add __meta_dns_name meta-label for the DNS-name. 
  
  - job_name: 'mongo'
    static_configs: 
      - targets: ['cloudstack_mymongodb:9001']
      
  - job_name: 'rabbitmq'
    metrics_path: '/api/metrics'
    static_configs: 
      - targets: ['cloudstack_rabbitmq:15672']