global: 
  scrape_interval: 30s
  scrape_timeout: 30s
  external_labels: 
    env: Cloud

rule_files: 
  - /etc/prometheus/sample.rules

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'cloudPlatform'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    metrics_path: '/metrics/cloudstack'
    static_configs:
      - targets: ['cloudstack_filter-proxy:8080']

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'rabbit2mongo'
    static_configs:
      - targets: ['cloudstack_rabbit2mongo:8080']
  
  - job_name: 'mongo'
    static_configs: 
      - targets: ['cloudstack_mymongodb:9001']
      
  - job_name: 'rabbitmq'
    metrics_path: '/api/metrics'
    static_configs: 
      - targets: ['cloudstack_rabbitmq:15672']