global: 
  scrape_interval: 15s
  scrape_timeout: 12s
  external_labels: 
    env: Cloud
    
#remote_write:
#  write_relabel_configs:
#  - source_label: [__name__]
#    regex: to_expensive_to_write_to_long_term_storage.*
#    action: drop

rule_files:
  - /etc/prometheus/cloud.rules  
  - /etc/prometheus/sample.rules

scrape_configs:
- job_name: "cloudPlatform"
  honor_labels: true
  metrics_path: "/federate"
  params:
    match[]:
    - "{cl_aatd_sanalytics_slice=\"slice1\"}"
    - "{cl_aatd_sanalytics_subslice=\"cloud\"}"
  static_configs:
  - targets:
    - "prom_platform:9090"
#  - job_name: 'cloudPlatform'
#    metrics_path: '/federate'
#    honor_labels: true
#    params:
#      'match[]':
#        - '{cl_cd_stack_namespace="cloudstack"}'
#    static_configs:
#      - targets: ['prom_platform:9090'] 

- job_name: 'rabbit2mongo'
  dns_sd_configs:
  - names:  
    - 'tasks.cloudstack_rabbit2mongo'
    type: 'A'
    port: 8080
    #TODO add __meta_dns_name meta-label for the DNS-name. 

- job_name: 'mongo'
  static_configs: 
    - targets: ['cloudstack_mymongodb:9001']
    
- job_name: 'rabbitmq'
  metrics_path: '/api/metrics'
  static_configs: 
    - targets: ['cloudstack_rabbitmq:15672']