global: 
  scrape_interval: 30s
  scrape_timeout: 30s
  external_labels: 
    env: NFV

rule_files:
  - /etc/prometheus/nfv.rules 
  - /etc/prometheus/sample.rules

scrape_configs:
  - job_name: 'nodex'
    dns_sd_configs:
    - names: 
      - 'tasks.nodex'
      type: 'A'
      port: 9100

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'nfvPlatform'
    metrics_path: '/metrics/nfvstack'
    static_configs:
      - targets: ['nfvstack_filter-proxy:8080']
    metric_relabel_configs: 
    - regex: 'container_label_com_docker_(.*)'
      action: labelmap
      replacement: 'cl_cd_${1}'
            

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'cep'
    static_configs:
      - targets: ['nfvstack_cep:8080']
  