global: 
  scrape_interval: 30s
  scrape_timeout: 30s
  external_labels: 
    env: IoT

rule_files: 
  - /etc/prometheus/iot.rules 
  - /etc/prometheus/sample.rules

scrape_configs:
  - job_name: 'iotPlatform'
    metrics_path: '/federate'
    honor_labels: true
    params:
      'match[]':
        - '{cl_cd_stack_namespace="iotstack"}'
    static_configs:
      - targets: ['prom_platform:9090']   

  - job_name: 'iot2nfvBridge'
    dns_sd_configs:
    - names:
      - 'tasks.iotstack_iot2nfvBridge'
      type: 'A'
      port: 8080
