scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'platform'

    # Override the global default and scrape targets from this job every 10 seconds.
    scrape_interval: 30s
    scrape_timeout: 30s

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    metrics_path: '/metrics/mystack'
    static_configs:
      - targets: ['filter-proxy:8080']

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'cep'

    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 30s
    scrape_timeout: 30s

    static_configs:
      - targets: ['cep.mystack:8080', 'mystack_cep:8080', 'cep:8080']
  
  - job_name: 'mongo'
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs: 
      - targets: ['mymongodb.mystack:9001', 'mystack_mymongodb:9001', 'mymongodb:9001']
      
  - job_name: 'rabbitmq'
    scrape_interval: 30s
    scrape_timeout: 30s
    metrics_path: '/api/metrics'
    static_configs: 
      - targets: ['rabbitmq.mystack:15672', 'mystack_rabbitmq:15672', 'rabbitmq:15672']