global: 
  scrape_interval: 30s
  scrape_timeout: 30s
  external_labels: 
    env: NFV

rule_files:
  - /etc/prometheus/nfv.rules 
  - /etc/prometheus/sample.rules

scrape_configs:
  - job_name: 'nfvPlatform'
    metrics_path: '/federate'
    honor_labels: true
    params:
      'match[]':
        - '{cl_cd_stack_namespace="nfvstack"}'
    static_configs:
      - targets: ['prom_platform:9090'] 
            

  - job_name: 'cep'
    dns_sd_configs:
      - names:
        - 'tasks.cep'
        type: 'A'
        port: 8080
 