global: 
  scrape_interval: 30s
  scrape_timeout: 30s
  external_labels: 
    env: IoT
    slice: s1
    station: s2

rule_files:
  - /etc/prometheus/iot-S1S2.rules 
  - /etc/prometheus/sample.rules

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'iotPlatform'
    metrics_path: '/federate'
    honor_labels: true
    params:
      'match[]':
        - '{cl_cd_stack_namespace="iotstackS1S2"}'
    static_configs:
      - targets: ['prom_platform:9090'] 

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
#  - job_name: 'iot2nfvBridge'
#    static_configs:
#      - targets: ['iotstack_iot2nfvBridge:8080']
