global: 
  scrape_interval: 30s
  scrape_timeout: 30s
  external_labels: 
    env: Cloud2
    slice: s2
    
  remote_write:
    write_relabel_configs:
    - source_label: [__name__]
      regex: to_expensive_to_write_to_long_term_storage.*
      action: drop

rule_files: 
  - /etc/prometheus/sample.rules
  - /etc/prometheus/cloud.rules

scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'cloudPlatform'
    metrics_path: '/federate'
    honor_labels: true
    params:
      'match[]':
        - '{cl_cd_stack_namespace="cloudstackS2"}'
    static_configs:
      - targets: ['prom_platform:9090'] 

  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'rabbit2mongo'
    static_configs:
      - targets: ['rabbit2mongo:8080']
  
  - job_name: 'mongo'
    static_configs: 
      - targets: ['mymongodb:9001']
      
  - job_name: 'rabbitmq'
    metrics_path: '/api/metrics'
    static_configs: 
      - targets: ['rabbitmq:15672']