version: "3"
services:

# ---------- monitoring services ---------------
    
  prometheus:
    #docker service create -p 9090:9090 --mount type=bind,source=/mastergit/sanalytics/sampleapps/prom/prometheus.yml,target=/etc/prometheus/prometheus.yml --name=prometheus --network="custom_monitoring" --network="mystack_app_overlay" --env INFLUXDB_PW=password --container-label sanalytics.slice="slice0" prom/prometheus -config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -web.console.libraries=/etc/prometheus/console_libraries -web.console.templates=/etc/prometheus/consoles -storage.remote.influxdb-url http://influx:8086 -storage.remote.influxdb.database mytestdb -storage.remote.influxdb.retention-policy "autogen" -storage.remote.influxdb.username username 
    image: prom/prometheus
    deploy: 
      resources: 
        limits: 
          memory: 180M
          cpus: "1.0"
    ports: 
      - "9091:9090"  # 9090 is always the platform-prometheus port
    volumes:  
      - /home/docker-user/sanalytics/configs/prom:/etc/prometheus/
      - /home/docker-user/sanalytics/data/S1/prom:/prometheus
      #- /mastergit/sanalytics/sampleapps/prom/sample.rules:/etc/prometheus/sample.rules
    networks:
      - cloudstackS1_app_overlay
      - platform_overlay
    command: 
      - -config.file=/etc/prometheus/prometheus-S1-cloud.yml
      - -storage.local.path=/prometheus
      - -web.console.libraries=/etc/prometheus/console_libraries
      - -web.console.templates=/etc/prometheus/consoles  
      - -storage.local.memory-chunks=102400
      - -storage.remote.influxdb-url=http://globalmonitoring.sanalytics.tk:8086 
      - -storage.remote.influxdb.database=s1db
      - -storage.remote.influxdb.retention-policy=autogen 
      - -storage.remote.influxdb.username=s1user      
    environment: 
      - INFLUXDB_PW=s1password
        
networks:
  cloudstackS1_app_overlay:
    external: true
  platform_overlay:
    external: true