version: "3.4"
x-slicemon:
  slicename: "slice1"
  subslice: "cloud"
services:

# ---------- application services ---------------

  mymongodb:
    image: cproinger/mongo-with-prom-exporter
    #image: mongo:3.4.1
    #bug https://github.com/docker/docker/issues/30297
    labels:
      at.ac.tuwien.dsg.sanalytics.slice : "slice1"
      at.ac.tuwien.dsg.sanalytics.subslice : "cloud"
    deploy:
      labels:
        at.ac.tuwien.dsg.sanalytics.metricsport : "9100"
      resources: 
        limits: 
          memory: 200M
          cpus: "0.25"
    ports:
      - "27017:27017"
    networks:
      - app_overlay
      
  rabbitmq: 
    image: cproinger/rabbitmq-management-monitoring
    labels:
      at.ac.tuwien.dsg.sanalytics.slice : "slice1"
      at.ac.tuwien.dsg.sanalytics.subslice : "cloud"
    deploy:
      labels:
        at.ac.tuwien.dsg.sanalytics.metricsport : "15672"
      resources: 
        limits: 
          memory: 120M
          cpus: "0.25"
    ports: 
      - "5672:5672"
      - "15672:15672"      
    networks:
      - app_overlay   
      
  rabbit2mongo:
    depends_on:
      - mymongodb
      - mqtt
    image: cproinger/sample-bridge
    labels:
      at.ac.tuwien.dsg.sanalytics.slice : "slice1"
      at.ac.tuwien.dsg.sanalytics.subslice : "cloud"    
    deploy:
      labels:
        at.ac.tuwien.dsg.sanalytics.metricsport : "8080"
      resources: 
        limits: 
          memory: 180M
          cpus: "0.5"
    ports:
      - "8081:8080"
    networks:
      - app_overlay   
    environment: 
      - JAVA_OPTS=-server -Xmx100m -XX:MaxMetaspaceSize=64m -Dspring.profiles.active=inbound-rabbitmq,forwarder,outbound-mongo -Dspring.rabbitmq.host=rabbitmq -Dspring.rabbitmq.username=guest -Dspring.rabbitmq.password=guest -Dspring.data.mongodb.uri=mongodb://mymongodb:27017/events


# ---------- monitoring services ---------------
    
  prometheus:
    image: prom/prometheus:v1.5.3
    deploy: 
      resources: 
        limits: 
          memory: 180M
          cpus: "1.0"
    ports: 
      - "9091:9090"  
    volumes: 
      - /mastergit/sanalytics/sampleapps/prom/:/etc/prometheus/
      # strange error https://github.com/prometheus/prometheus/issues/1600
      #- /c/Users/cproinger/Documents/Docker/prom/cloud:/prometheus
      #- /mastergit/sanalytics/sampleapps/prom/sample.rules:/etc/prometheus/sample.rules
    networks:
      - app_overlay
      - platform_overlay
      - globmonstack_monitoring_overlay
    depends_on: 
    # these do not need to be defined regarding DNS resolution of the names (just if you are wondering)
      - mymongodb
      - rabbitmq
      - influx
    command: 
      - -config.file=/etc/prometheus/prometheus-cloud.yml
      - -storage.local.path=/prometheus
      - -web.console.libraries=/etc/prometheus/console_libraries
      - -web.console.templates=/etc/prometheus/consoles  
      - -storage.remote.influxdb-url=http://influx:8086 
      - -storage.remote.influxdb.database=mytestdb 
      - -storage.remote.influxdb.retention-policy=autogen 
      - -storage.remote.influxdb.username=username      
    environment: 
      - INFLUXDB_PW=password

networks:
  app_overlay: 
  globmonstack_monitoring_overlay: 
    external: true
  platform_overlay:
    external: true