version: "3"
services:

# ---------- application services ---------------
  
  mqtt:
    image: toke/mosquitto:release-1.4.10-2
    deploy: 
      resources: 
        limits: 
          memory: 10M
    ports:
      - "1884:1883"
    networks:
      - iot_overlay      
    
  sensor:
    depends_on:
      - mqtt
    image: cproinger/sample-sensor
    deploy: 
      resources: 
        limits: 
          memory: 128M
    networks:
      - iot_overlay
    environment: 
      - JAVA_OPTS=-Xmx16m -Dspring.profiles.active=random -Dmqtt.brokerURL=tcp://iotstack_mqtt:1883     
      
  iot2nfvBridge:
    depends_on:
      - mqtt
    image: cproinger/sample-bridge
    deploy: 
      resources: 
        limits: 
          memory: 128M
    networks:
      - iot_overlay
      - nfvstack_app_overlay
    environment: 
      - JAVA_OPTS=-Xmx100m -Dspring.profiles.active=inbound-mqtt,forwarder,outbound-mqtt -Dinbound-mqtt.brokerURL=tcp://iotstack_mqtt:1883 -Doutbound-mqtt.brokerURL=tcp://nfvstack_mqtt:1883      

# ---------- monitoring services ---------------
    
  iot_prometheus:
    image: prom/prometheus:v1.5.3
    ports: 
      - "9093:9090"  
    volumes: 
      - /mastergit/sanalytics/sampleapps/prom/:/etc/prometheus/
      #- /mastergit/sanalytics/sampleapps/prom/sample.rules:/etc/prometheus/sample.rules
    networks:
      - iot_overlay
      - monitoring_overlay
      - cloudstack_monitoring_overlay
      - platform_overlay
    depends_on: 
    # these do not need to be defined regarding DNS resolution of the names (just if you are wondering)
      - iot2nfvBridge
    command: 
      - -config.file=/etc/prometheus/prometheus-iot.yml
      - -storage.local.path=/prometheus
      - -web.console.libraries=/etc/prometheus/console_libraries
      - -web.console.templates=/etc/prometheus/consoles  
      - -storage.remote.influxdb-url=http://influx:8086 
      - -storage.remote.influxdb.database=mytestdb 
      - -storage.remote.influxdb.retention-policy=autogen 
      - -storage.remote.influxdb.username=username      
    environment: 
      - INFLUXDB_PW=password
    
networks:
  iot_overlay: 
  monitoring_overlay:
  cloudstack_monitoring_overlay:
    external: true    
  nfvstack_app_overlay:
    external: true 
  platform_overlay:
    external: true