version: "3"
services:

# ---------- application services ---------------

      
  cep:
    depends_on:
      - mqtt
    image: cproinger/sample-bridge
    deploy: 
      resources: 
        limits: 
          memory: 180M
          cpus: "0.1"
    ports:
      - "8082:8080"
    networks:
      - app_overlay  
      - cloudstack_app_overlay 
    environment: 
      - JAVA_OPTS=-server -Xmx100m -XX:MaxMetaspaceSize=64m -Dspring.profiles.active=inbound-mqtt,esper-cep-randomcount,outbound-rabbitmq -Dinbound-mqtt.brokerURL=tcp://nfvstack_mqtt:1883 -Dinbound-mqtt.subscriptions=sensor/+/randomcount -Dspring.rabbitmq.host=cloudstack_rabbitmq -Dspring.rabbitmq.username=guest -Dspring.rabbitmq.password=guest
    
    
  mqtt:
    image: toke/mosquitto:release-1.4.10-2
    deploy: 
      resources: 
        limits: 
          memory: 10M
          cpus: "0.5"          
    ports:
      - "1883:1883"
    networks:
      - app_overlay   

# ---------- monitoring services ---------------
    
  prometheus:
    image: prom/prometheus:v1.5.3
    ports: 
      - "9092:9090"  
    volumes: 
      - /mastergit/sanalytics/sampleapps/prom/:/etc/prometheus/
      # strange error https://github.com/prometheus/prometheus/issues/1600
      #- /c/Users/cproinger/Documents/Docker/prom/nfv:/prometheus      
      #- /mastergit/sanalytics/sampleapps/prom/sample.rules:/etc/prometheus/sample.rules
    networks:
      - app_overlay
      - monitoring_overlay
      - cloudstack_monitoring_overlay
      - platform_overlay
    depends_on: 
    # these do not need to be defined regarding DNS resolution of the names (just if you are wondering)
      - cep
    command: 
      - -config.file=/etc/prometheus/prometheus-nfv.yml
      - -storage.local.path=/prometheus
      - -web.console.libraries=/etc/prometheus/console_libraries
      - -web.console.templates=/etc/prometheus/consoles
      # TODO memory usage verringern. 
      #- -storage.local.target-heap-size=104857600 # 100 MB.
      #- -storage.remote.influxdb-url=http://influx:8086 -> invalid URL ??? WTF!
      # *banging head against table* -> https://github.com/prometheus/prometheus/issues/2022  
      - -storage.remote.influxdb-url=http://influx:8086 
      - -storage.remote.influxdb.database=mytestdb 
      - -storage.remote.influxdb.retention-policy=autogen 
      - -storage.remote.influxdb.username=username      
    environment: 
      - INFLUXDB_PW=password
    
networks:
  app_overlay: 
  monitoring_overlay: 
  platform_overlay:
    external: true
  cloudstack_monitoring_overlay:
    external: true    
  cloudstack_app_overlay:
    external: true        