version: "3"

services:
# there is a bug with stack deploy and global service
# http://stackoverflow.com/questions/41934123/docker-1-13-stack-deploy-with-global-service-malfunction-target-replicas-increa
  cadvisor:
    image: google/cadvisor:latest
    deploy: 
      mode: global  
    volumes:
      - /:/rootfs:ro
      - /var/run:/var:ro
      - /sys/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - app_overlay
      
networks: 
  app_overlay:        