version: "3"
services:

  mymongodb:
    image: cproinger/mongo-with-prom-exporter
    #image: mongo:3.4.1
    #bug https://github.com/docker/docker/issues/30297
    #lables: 
    #  sanalytics.slice: "slice0"
    deploy:
      labels:
        sanalytics.slice: "slice0"
    ports:
      - "27017:27017"
    networks:
      - app_overlay

  cep:
    depends_on:
      - mymongodb
      - mqtt
    image: cproinger/sample-cep
    ports:
      - "8081:8080"
    networks:
      - app_overlay
    
  mqtt:
    image: toke/mosquitto:release-1.4.10-2
    ports:
      - "1883:1883"
    networks:
      - app_overlay      
    
  sensor:
    depends_on:
      - mqtt
    image: cproinger/sample-sensor
    networks:
      - app_overlay            
    
# monitoring services
  cadvisor:
    image: google/cadvisor:latest
    deploy: 
      mode: global  
    volumes:
      - /:/rootfs:ro
      - /var/run:/var:ro
      - /sys/sys:ro
      - /var/lib/docker:/var/lib/docker:ro
    networks:
      - app_overlay 
  
  filter-proxy:
    image: cproinger/sanalytics-filter-proxy
    ports: 
      - "8080:8080"  
    networks:
      - app_overlay
    depends_on: 
      - cadvisor
      - cep
    environment: 
      - JAVA_OPTS=-Xmx256m -Dsanalytics.slice.label=com.docker.stack.namespace -Dtarget.dnsname=cadvisor

  prometheus:
    #docker service create -p 9090:9090 --mount type=bind,source=/mastergit/sanalytics/sampleapps/prom/prometheus.yml,target=/etc/prometheus/prometheus.yml --name=prometheus --network="custom_monitoring" --network="mystack_app_overlay" --env INFLUXDB_PW=password --container-label sanalytics.slice="slice0" prom/prometheus -config.file=/etc/prometheus/prometheus.yml -storage.local.path=/prometheus -web.console.libraries=/etc/prometheus/console_libraries -web.console.templates=/etc/prometheus/consoles -storage.remote.influxdb-url http://influx:8086 -storage.remote.influxdb.database mytestdb -storage.remote.influxdb.retention-policy "autogen" -storage.remote.influxdb.username username 
    image: prom/prometheus
    ports: 
      - "9090:9090"  
    volumes: 
      - /mastergit/sanalytics/sampleapps/prom/prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - app_overlay
      - monitoring_overlay
    depends_on: 
      - filter-proxy
      - mymongodb
      - cep
    command: 
      - -config.file=/etc/prometheus/prometheus.yml
      - -storage.local.path=/prometheus
      - -web.console.libraries=/etc/prometheus/console_libraries
      - -web.console.templates=/etc/prometheus/consoles  
      - -storage.remote.influxdb-url=http://influx:8086 
      - -storage.remote.influxdb.database=mytestdb 
      - -storage.remote.influxdb.retention-policy="autogen" 
      - -storage.remote.influxdb.username=username      
    environment: 
      - INFLUXDB_PW=password
           
           
networks:
  app_overlay: 
  monitoring_overlay:  