version: "3"
services:

  mymongodb:
    image: cproinger/mongo-with-prom-exporter
    #image: mongo:3.4.1
    #bug https://github.com/docker/docker/issues/30297
    #lables: 
    #  sanalytics.slice: "slice0"
    deploy:
    #  labels:
    #    sanalytics.slice: "slice0"
      resources: 
        limits: 
          memory: 200M
    ports:
      - "27017:27017"
    networks:
      - app_overlay

  cep:
    depends_on:
      - mymongodb
      - mqtt
    image: cproinger/sample-cep
    deploy: 
      resources: 
        limits: 
          memory: 200M
    ports:
      - "8081:8080"
    networks:
      - app_overlay      
    
  mqtt:
    image: toke/mosquitto:release-1.4.10-2
    deploy: 
      resources: 
        limits: 
          memory: 10M
    ports:
      - "1883:1883"
    networks:
      - app_overlay      
    
  sensor:
    depends_on:
      - mqtt
    image: cproinger/sample-sensor
    deploy: 
      resources: 
        limits: 
          memory: 128M
    networks:
      - app_overlay
    environment: 
      - JAVA_OPTS=-Xmx16m  -Dmqtt.brokerURL=tcp://mqtt:1883     
    
networks:
  app_overlay: 