version: "3"
services:

# ---------- application services ---------------
  
  mqtt:
    image: pascaldevink/rpi-mosquitto:1.0
    deploy: 
      resources: 
        limits: 
          memory: 10M
    ports:
      - "1884:1883"
    networks:
      - app_overlay      
    
  sensor:
    depends_on:
      - mqtt
    image: cproinger/rpi-sample-sensor
    deploy: 
      resources: 
        limits: 
          memory: 128M
    networks:
      - app_overlay
    environment: 
      - JAVA_OPTS=-Xmx16m  -Dmqtt.brokerURL=tcp://iotstack_mqtt:1883     
      
  iot2nfvBridge:
    depends_on:
      - mqtt
    image: cproinger/rpi-sample-bridge
    deploy: 
      resources: 
        limits: 
          memory: 128M
    networks:
      - app_overlay
      - nfvstack_app_overlay
    environment: 
      - JAVA_OPTS=-Xmx100m -Dspring.profiles.active=inbound-mqtt,forwarder,outbound-mqtt -Dinbound-mqtt.brokerURL=tcp://iotstack_mqtt:1883 -Doutbound-mqtt.brokerURL=tcp://nfvstack_mqtt:1883      
   
networks:
  app_overlay:    
  nfvstack_app_overlay:
    external: true 